language: groovy
jdk:
  - oraclejdk7
script: "./grailsw refresh-dependencies && ./grailsw test-app unit:"
language: groovy

before_script:
  - chmod +x grailsw

before_deploy:
    - chmod +x grailsw

deploy:
  provider: heroku
  api_key: "683a3567-4907-46ef-a428-2949db6bdef6"
  app: ivvq-shapp
